# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 500e51d32ce9d7dca705d8b14a2ef364e6708c4218cb5b48bf6f0f9132b1a2e9c81cb70479ec6b821d04349d3e3023ee0b05f7a38b96592a9e4c9004c32e5bb7

test:
  secret_key_base: a8906ab4e44b090d298bcf384d70f71eb8631b769035276dfdc4ecaa180af5c70a2fe0a1dfe0bd5842a7bef3b16f8e212ea4d8a47ff5d90fc58594bb7cff7b3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
